/**
 * The trust boundary. Everything above this divider is observed and
 * deterministic; everything below it is AI inference or downstream execution.
 */
export function AIAnalysisBoundary() {
  return (
    <div
      role="separator"
      aria-label="Trust boundary: observed data above, AI analysis below"
      className="flex items-center gap-4 py-1"
    >
      <span aria-hidden className="h-px flex-1 bg-gray-200" />
      <span className="whitespace-nowrap text-[11px] font-semibold uppercase tracking-[0.14em] text-gray-400">
        AI Analysis · Generated by LLM
      </span>
      <span aria-hidden className="h-px flex-1 bg-gray-200" />
    </div>
  );
}
